# FIXME: currently just builds it, eventually, should use qemu to try to run
# the image (potentially as a separate action)
name: build-image-arm64

on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout project
        uses: actions/checkout@v2
      - name: build image
        run: apt install -y qemu-user-static binfmt-support && docker run --mount type=bind,source=$PWD,target=/PrawnOS
             --privileged -v/dev:/dev debian:bullseye
             /bin/bash /PrawnOS/tests/build-image.sh "$GITHUB_SHA" arm64 Shiba
      - name: publish image
        uses: actions/upload-artifact@v2
        with:
          name: "PrawnOS-Shiba-arm64-git-${{ github.sha }}.img.xz"
          path: "PrawnOS-Shiba-arm64-git-${{ github.sha }}.img.xz"
