# FIXME: currently just builds it, eventually, should use qemu to try to run
# the image (potentially as a separate action)
name: build-image-armhf

on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout project
        uses: actions/checkout@v3
      - name: build image
        run: sudo dpkg -i ./tests/resources/qemu-user-static_5.1+dfsg-4+b1_amd64.deb && 
             docker run --mount type=bind,source=$PWD,target=/PrawnOS
             --privileged -v/dev:/dev debian:bullseye
             /bin/bash /PrawnOS/tests/build-image.sh "$GITHUB_SHA" armhf Shiba
      - name: publish image
        uses: actions/upload-artifact@v4
        with:
          name: "PrawnOS-Shiba-armhf-git-${{ github.sha }}.img.xz"
          path: "PrawnOS-Shiba-armhf-git-${{ github.sha }}.img.xz"
